// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SacramentPlanner.Models;

namespace SacramentPlanner.Migrations
{
    [DbContext(typeof(SacramentPlannerContext))]
    partial class SacramentPlannerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SacramentPlanner.Models.Sacrament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CloseHymn");

                    b.Property<string>("ClosePrayer");

                    b.Property<string>("Conducting");

                    b.Property<DateTime>("Date");

                    b.Property<int?>("IntermediateHymn");

                    b.Property<int>("OpenHymn");

                    b.Property<string>("OpenPrayer");

                    b.Property<int>("SacramentHymn");

                    b.Property<string>("Speaker");

                    b.Property<string>("Subject");

                    b.HasKey("Id");

                    b.ToTable("Sacrament");
                });
#pragma warning restore 612, 618
        }
    }
}
